services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-core-postgres
    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: banking
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
